[package]
name = "five_letters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
colored = "2.1.0"
rand = "0.8.5"
titlecase = "2.2.1"
